In [2]:
from calendar import day_name
from webbrowser import open_new

import pandas as pd
import numpy as np
from datetime import timedelta

In [3]:
customers = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_customers_dataset.csv')
geolocation = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_geolocation_dataset.csv')
order_items = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_items_dataset.csv')
order_payment = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_payments_dataset.csv')
order_review = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_reviews_dataset.csv')
orders = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_orders_dataset.csv')
products = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_products_dataset.csv')
sellers = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_sellers_dataset.csv')
products_category_name_translation = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/product_category_name_translation.csv')

In [4]:
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

orders['order_delivered_customer_date'] = pd.to_datetime(
    orders['order_delivered_customer_date']
)

In [5]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [6]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [7]:
products_category_name_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [8]:
order_product_details = order_items.merge(products[['product_id','product_category_name']], on='product_id',how='left')
order_product_details = order_product_details.merge(products_category_name_translation, on='product_category_name',how='left')
order_product_details.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim,garden_tools

In [9]:
df= order_product_details.groupby('product_category_name_english')['price'].sum().reset_index().sort_values(by='price', ascending=False)

In [10]:
temp_df = order_product_details.groupby('product_category_name_english')['order_id'].nunique().reset_index().sort_values(by='order_id', ascending=False)

In [11]:
numberof_products_items_sold=order_product_details.groupby('product_category_name_english')['order_id'].count().reset_index().sort_values(by='order_id', ascending=False)
numberof_products_items_sold.head(10)

   product_category_name_english  order_id
7                 bed_bath_table     11115
43                 health_beauty      9670
65                sports_leisure      8641
39               furniture_decor      8334
15         computers_accessories      7827
49                    housewares      6964
70                 watches_gifts      5991
68                     telephony      4545
42                  garden_tools      4347
5                           auto      4235

In [12]:
op_df=df.merge(temp_df, on='product_category_name_english', how='left')

In [13]:
op_df['Avg_sels_values_per_order']=op_df['price']/op_df['order_id']

In [14]:
op_df.head()

,product_category_name_english,price,order_id,Avg_sels_values_per_order
0,health_beauty,1258681.34,8836,142.449224
1,watches_gifts,1205005.68,5624,214.261323
2,bed_bath_table,1036988.68,9417,110.118794
3,sports_leisure,988048.97,7720,127.985618
4,computers_accessories,911954.32,6689,136.336421

In [15]:
order_product_details.groupby('product_category_name_english')['price'].mean().reset_index().sort_values(by='price', ascending=False).head(10)

            product_category_name_english        price
14                              computers  1098.340542
64  small_appliances_home_oven_and_coffee   624.285658
45                      home_appliances_2   476.124958
0              agro_industry_and_commerce   342.124858
56                    musical_instruments   281.616000
63                       small_appliances   280.778468
34                        fixed_telephony   225.693182
19              construction_tools_safety   208.992371
70                          watches_gifts   201.135984
1                        air_conditioning   185.269226

In [16]:
avg_sales = op_df['price'].mean()
avg_orders = op_df['order_id'].mean()
print(avg_sales)
print(avg_orders)

188825.26676056333
1380.2394366197184

In [17]:
def category_classfication(row):
    if row['price'] > avg_sales and row['order_id'] > avg_orders:
        return 'High + High'
    elif row['price'] < avg_sales and row['order_id'] < avg_orders:
        return 'Low + Low'
    elif row['price'] > avg_sales and row['order_id'] < avg_orders:
        return 'High + Low'
    else:
        return 'Low + High'

In [18]:
op_df['segment'] = op_df.apply(category_classfication,axis=1)
op_df['segment'].value_counts()

segment
Low + Low      49
High + High    16
High + Low      4
Low + High      2
Name: count, dtype: int64

In [21]:
op_df.to_csv('category_revenue.csv', index=False)