In [1]:
from calendar import day_name
from webbrowser import open_new

import pandas as pd
import numpy as np
from datetime import timedelta

In [4]:
customers = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_customers_dataset.csv')
geolocation = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_geolocation_dataset.csv')
order_items = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_items_dataset.csv')
order_payment = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_payments_dataset.csv')
order_review = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_order_reviews_dataset.csv')
orders = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_orders_dataset.csv')
products = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_products_dataset.csv')
sellers = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/olist_sellers_dataset.csv')
products_category_name_translation = pd.read_csv('C:/AIML/software side/olist_analisys/data/raw/product_category_name_translation.csv')
category_revenue = pd.read_csv('C:/AIML/software side/olist_analisys/data/processed/category_revenue.csv')

In [5]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [7]:
category_revenue['avg_revenue_per_order'] = (category_revenue['price'] / category_revenue['order_id'])
category_revenue.head()

,product_category_name_english,price,order_id,Avg_sels_values_per_order,segment,avg_revenue_per_order
0,health_beauty,1258681.34,8836,142.449224,High + High,142.449224
1,watches_gifts,1205005.68,5624,214.261323,High + High,214.261323
2,bed_bath_table,1036988.68,9417,110.118794,High + High,110.118794
3,sports_leisure,988048.97,7720,127.985618,High + High,127.985618
4,computers_accessories,911954.32,6689,136.336421,High + High,136.336421

In [13]:
category_revenue.sort_values(by='avg_revenue_per_order',ascending=False).head(10)

,product_category_name_english,price,order_id,Avg_sels_values_per_order,segment,avg_revenue_per_order
16,computers,222963.13,181,1231.840497,High + Low,1231.840497
34,small_appliances_home_oven_and_coffee,47445.71,75,632.609467,Low + Low,632.609467
25,home_appliances_2,113317.74,234,484.263846,Low + Low,484.263846
28,agro_industry_and_commerce,72530.47,182,398.519066,Low + Low,398.519066
18,musical_instruments,191498.88,628,304.934522,High + Low,304.934522
19,small_appliances,190648.58,630,302.616794,High + Low,302.616794
30,fixed_telephony,59583.00,217,274.576037,Low + Low,274.576037
38,construction_tools_safety,40544.52,167,242.781557,Low + Low,242.781557
32,air_conditioning,55024.96,253,217.489960,Low + Low,217.489960
14,office_furniture,273960.70,1273,215.208720,High + Low,215.208720

In [26]:
top_avg_revanue = category_revenue.sort_values(by='avg_revenue_per_order',ascending=False).head(2)
top_avg_revanue

,product_category_name_english,price,order_id,Avg_sels_values_per_order,segment,avg_revenue_per_order
16,computers,222963.13,181,1231.840497,High + Low,1231.840497
34,small_appliances_home_oven_and_coffee,47445.71,75,632.609467,Low + Low,632.609467

In [27]:
top_order_volume = category_revenue.sort_values(by='order_id',ascending=False).head(2)
top_order_volume

,product_category_name_english,price,order_id,Avg_sels_values_per_order,segment,avg_revenue_per_order
2,bed_bath_table,1036988.68,9417,110.118794,High + High,110.118794
0,health_beauty,1258681.34,8836,142.449224,High + High,142.449224

In [37]:
category_revenue[category_revenue['segment'] == 'Low + Low'].sort_values(by='price').head(3)

,product_category_name_english,price,order_id,Avg_sels_values_per_order,segment,avg_revenue_per_order
70,security_and_services,283.29,2,141.645000,Low + Low,141.645000
69,fashion_childrens_clothes,569.85,8,71.231250,Low + Low,71.231250
68,cds_dvds_musicals,730.00,12,60.833333,Low + Low,60.833333

In [41]:
top_5 = category_revenue.sort_values(by='price', ascending=False).head(5)
top_5_revenue = top_5['price'].sum()
total_revenue = category_revenue['price'].sum()
revenue_share = (top_5_revenue / total_revenue) * 100
print("Top 5 Categories Revenue:", top_5_revenue)
print("Total Revenue:", total_revenue)
print("Top 5 Revenue Share:", round(revenue_share, 2), "%")

Top 5 Categories Revenue: 5400678.99
Total Revenue: 13406593.939999998
Top 5 Revenue Share: 40.28 %